# Generated by Django 4.1.7 on 2023-08-01 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_user_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=50)),
                ('phone_number', models.CharField(max_length=12)),
                ('zip_code', models.IntegerField()),
                ('building', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('total_quantity', models.IntegerField()),
                ('total_price', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_orders', to='users.user')),
            ],
            options={
                'db_table': 'Orders',
            },
        ),
    ]
