# Generated by Django 4.1.7 on 2023-07-19 03:12

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='name')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('description', models.CharField(max_length=100, verbose_name='description')),
                ('price', models.IntegerField(verbose_name='price')),
                ('category', models.CharField(choices=[('Shirts', 'Shirts'), ('Bottoms', 'Bottoms'), ('Caps', 'Caps'), ('T-Shirts', 'T-Shirts')], max_length=20)),
            ],
            options={
                'db_table': 'Products',
            },
        ),
    ]
