# Generated by Django 4.1.7 on 2023-07-19 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
        migrations.AddField(
            model_name='products',
            name='gender',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women')], default='Male', max_length=20),
            preserve_default=False,
        ),
    ]
